#!/bin/bash
echo "Simple MySQL setup for Rentala Tenants"
echo ""
echo "Run this command (replace YOURPASSWORD if you have one):"
echo ""
echo "\"/c/Program Files/MySQL/MySQL Server 9.5/bin/mysql.exe\" -u root -p rentala < setup_tenants.sql"
echo ""
echo "If no password, run:"
echo "\"/c/Program Files/MySQL/MySQL Server 9.5/bin/mysql.exe\" -u root rentala < setup_tenants.sql"
echo ""
echo "Or manually:"
echo "1. \"C:\\Program Files\\MySQL\\MySQL Server 9.5\\bin\\mysql.exe\" -u root -p"
echo "2. Enter password (press Enter if no password)"
echo "3. Run: CREATE DATABASE IF NOT EXISTS rentala;"
echo "4. Run: USE rentala;"
echo "5. Copy/paste the SQL from setup_tenants.sql"
